spring:
  server:
    port: 8081
  kafka:
    topic : trucks-events
    template:
      default-topic: trucks-events
    consumer:
      bootstrap-servers:  localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: library-events-listener-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/truck_crm
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

